// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsbzQP5OiHu0UnaKrvDQb0nweiGRwufDg',
    appId: '1:994653038687:web:d922d7f24e16f31045d3ea',
    messagingSenderId: '994653038687',
    projectId: 'chat-app-fe80e',
    authDomain: 'chat-app-fe80e.firebaseapp.com',
    storageBucket: 'chat-app-fe80e.firebasestorage.app',
    measurementId: 'G-B1MC1SMRCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUnOxOH8jrd2EDu-ZuRM9UpOh0jP7ZC5g',
    appId: '1:994653038687:android:1bcb0a2ea6677aca45d3ea',
    messagingSenderId: '994653038687',
    projectId: 'chat-app-fe80e',
    storageBucket: 'chat-app-fe80e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkPkp98wldTR2aUdML18N3Ss1getRJAxo',
    appId: '1:994653038687:ios:0009639c033d025345d3ea',
    messagingSenderId: '994653038687',
    projectId: 'chat-app-fe80e',
    storageBucket: 'chat-app-fe80e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkPkp98wldTR2aUdML18N3Ss1getRJAxo',
    appId: '1:994653038687:ios:0009639c033d025345d3ea',
    messagingSenderId: '994653038687',
    projectId: 'chat-app-fe80e',
    storageBucket: 'chat-app-fe80e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsbzQP5OiHu0UnaKrvDQb0nweiGRwufDg',
    appId: '1:994653038687:web:710a797d1f0822d245d3ea',
    messagingSenderId: '994653038687',
    projectId: 'chat-app-fe80e',
    authDomain: 'chat-app-fe80e.firebaseapp.com',
    storageBucket: 'chat-app-fe80e.firebasestorage.app',
    measurementId: 'G-WGXY19CS10',
  );
}
